name: Pre-merge tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: qa
    env:
      file_name: "TestReport.${{ github.event.number }}.${{github.run_number}}.md"
      title: "Test run for PR ${{ github.event.number }}"
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7"
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --logger:"liquid.md;LogFileName=${{github.workspace}}/${{env.file_name}};Title=${{env.title}};"
      - uses: actions/upload-artifact@v3
        with:
          name: 'Test report'
          path: ${{github.workspace}}/${{env.file_name}}
